CREATE TABLE IF NOT EXISTS ClassificationType (ID  INTEGER PRIMARY KEY NOT NULL, Classification VARCHAR(200) UNIQUE NOT NULL);

CREATE TABLE IF NOT EXISTS WORDLIST (ID  INTEGER PRIMARY KEY, WORD VARCHAR(200) UNIQUE NOT NULL, TotalCount BIGINT NOT NULL );

CREATE TABLE IF NOT EXISTS WORD_ClASSIFICATION (CLASS_ID  INTEGER NOT NULL, WORD_ID INTEGER NOT NULL, WordCount BIGINT NOT NULL, 
FOREIGN KEY (CLASS_ID) REFERENCES ClassificationType(ID),FOREIGN KEY (WORD_ID) REFERENCES WORDLIST(ID)  );
