CREATE TABLE IF NOT EXISTS ClassificationType (ID  INTEGER PRIMARY KEY, Classification VARCHAR(200) );

CREATE TABLE IF NOT EXISTS WORDLIST (ID  INTEGER PRIMARY KEY, WORD VARCHAR(200), TotalCount BIGINT );

CREATE TABLE IF NOT EXISTS WORD_ClASSIFICATION (CLASS_ID  INTEGER , WORD_ID INTEGER , WordCount BIGINT, 
FOREIGN KEY (CLASS_ID) REFERENCES ClassificationType(ID),FOREIGN KEY (WORD_ID) REFERENCES WORDLIST(ID)  );
